### PR TITLE
Issue13 builder add varargs

### PR DESCRIPTION
**Pull request by tmtron**
Builder.add with VarArgs #13

### CODE REVIEW

**Comment by tmtron** [comment]
Please don't merge this pull request yet. I just realized that there are some problems which were not covered by the test-cases:
The `add(varargs)` methods use a `HashSet` internally, and thus will ignore duplicates and change the order, which is not okay for sequential types: e.g. Array, etc
I'll fix that soon.

**Comment by io7m** [comment]
'Lo.

Nice work. One small thing: I think the `LinkedHashSet` change is wrong: It's still using a plain `HashSet` to receive the varargs, unless I'm mistaken.

**Comment by io7m** [comment]
Additionally: I think these changes will produce an API that's not binary compatible with code generated from previous releases. I'm not sure anyone cares about this though (we're not even at `1.0.0` yet, so the API/ABI isn't stable anyway).

**Comment by io7m** [comment]
Looks good to me. Thanks again!

**Comment by tmtron** [comment]
Did you forget to merge the pull-request when closing?  
I cannot see these changes in the develop branch yet: e.g. [VavrArrayEncoding.java](https://github.com/immutables/immutables-vavr/blob/develop/vavr-encodings/src/main/java/org/immutables/vavr/encodings/VavrArrayEncoding.java) does not have `addVarArgs`

**Comment by io7m** [comment]
Strange, I'm pretty sure I merged it. I'll re-open and try merging again (merging an already-merged change should either result in an error or a no-op).

**Comment by io7m** [comment]
That's better.

**Comment by tmtron** [comment]
Great - thanks.

**Pull request merged**
